"""operation type added

Revision ID: 7a0cfa6980c1
Revises: 204020938d27
Create Date: 2026-04-17 13:25:01.653247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a0cfa6980c1"
down_revision: Union[str, Sequence[str], None] = "204020938d27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operations", sa.Column("type", sa.String(length=7), nullable=False))
    op.create_index(op.f("ix_operations_type"), "operations", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_type"), table_name="operations")
    op.drop_column("operations", "type")
    # ### end Alembic commands ###
