"""user role added

Revision ID: 632db1874dfb
Revises: 13710c57472a
Create Date: 2026-04-21 14:23:12.846247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "632db1874dfb"
down_revision: Union[str, Sequence[str], None] = "13710c57472a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum("user", "admin", name="userrole", create_type=True)
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users", sa.Column("role", userrole_enum, server_default="user", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    userrole_enum = sa.Enum("user", "admin", name="userrole")
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
