"""indexes added

Revision ID: 204020938d27
Revises: 8d6abe11a393
Create Date: 2026-04-16 14:04:04.252417

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "204020938d27"
down_revision: Union[str, Sequence[str], None] = "8d6abe11a393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_operations_amount"), "operations", ["amount"], unique=False
    )
    op.create_index(
        op.f("ix_operations_description"), "operations", ["description"], unique=False
    )
    op.create_index(
        op.f("ix_operations_wallet_name"), "operations", ["wallet_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_wallet_name"), table_name="operations")
    op.drop_index(op.f("ix_operations_description"), table_name="operations")
    op.drop_index(op.f("ix_operations_amount"), table_name="operations")
    # ### end Alembic commands ###
