"""Wallet

Revision ID: d9b57e4c29db
Revises:
Create Date: 2026-04-15 20:00:46.538888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9b57e4c29db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint(
            "balance >= 0.0", name=op.f("ck_wallets_positive_balance_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_index(op.f("ix_wallets_name"), "wallets", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_name"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
