"""add indexes to wallet_id and user_id

Revision ID: 13710c57472a
Revises: 629600aa260d
Create Date: 2026-04-18 12:01:28.693327

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "13710c57472a"
down_revision: Union[str, Sequence[str], None] = "629600aa260d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_operations_wallet_id"), "operations", ["wallet_id"], unique=False
    )
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_operations_wallet_id"), table_name="operations")
    # ### end Alembic commands ###
