"""users

Revision ID: 629600aa260d
Revises: 7a0cfa6980c1
Create Date: 2026-04-17 20:29:05.168946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "629600aa260d"
down_revision: Union[str, Sequence[str], None] = "7a0cfa6980c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.add_column("wallets", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "unique_wallet_for_user", "wallets", ["user_id", "name"]
    )
    op.create_foreign_key(
        op.f("fk_wallets_user_id_users"), "wallets", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_wallets_user_id_users"), "wallets", type_="foreignkey")
    op.drop_constraint("unique_wallet_for_user", "wallets", type_="unique")
    op.drop_column("wallets", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
